#!/bin/bash
set -ex

check_cla() {
  local passchar="\xe2\x9c\x94" # U+2714 - ballot check
  local failchar="\xe2\x9c\x98" # U+2718 - ballot x
  local rc=0
  local IFS=$'\n'

  echo "Checking CONTRIBUTOR status..."
  for x in $(git log --pretty=format:'%aE %h - %s (%aN <%aE>)' \
                 ${TRAVIS_COMMIT_RANGE}); do
    email=${x%% *}
    desc=${x#* }
    if grep -q '^[^#].*<'${email}'>' CONTRIBUTORS; then
      echo -e "\033[32m${passchar}\033[0m $desc"
    else
      echo -e "\033[31m${failchar}\033[0m $desc"
      echo -e "  \033[31m<${email}> not listed in CONTRIBUTORS file!\033[0m"
      rc=1
    fi
  done
  echo

  return $rc
}

CPUS=4
WANT_CTAP=2.0.0
WANT_LIBSODIUM=1.0.8
WANT_LIBZMQ=4.1.4
WANT_LIBVIGOR=1.2.10
WANT_ZTK=0.1.1

mkdir tmp
BUILD_PREFIX=$PWD/tmp

CONFIG_OPTS=()
CONFIG_OPTS+=("CFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CPPFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CXXFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("LDFLAGS=-L${BUILD_PREFIX}/lib")
CONFIG_OPTS+=("PKG_CONFIG_PATH=${BUILD_PREFIX}/lib/pkgconfig")
CONFIG_OPTS+=("--prefix=${BUILD_PREFIX}")

LD_LIBRARY_PATH="${BUILD_PREFIX}/lib"
export LD_LIBRARY_PATH

# dep: ctap
curl -Ls https://github.com/jhunt/ctap/releases/download/v${WANT_CTAP}/ctap-${WANT_CTAP}.tar.gz | tar -xz
(cd ctap-${WANT_CTAP}; ./configure "${CONFIG_OPTS[@]}"; make -j${CPUS} install)

# dep: libsodium
curl -Ls https://github.com/jedisct1/libsodium/releases/download/${WANT_LIBSODIUM}/libsodium-${WANT_LIBSODIUM}.tar.gz | tar -xz
(cd libsodium-${WANT_LIBSODIUM}; ./configure "${CONFIG_OPTS[@]}"; make -j${CPUS} install)

# dep: libzmq
curl -Ls http://download.zeromq.org/zeromq-${WANT_LIBZMQ}.tar.gz | tar -xz
(cd zeromq-${WANT_LIBZMQ}; ./configure "${CONFIG_OPTS[@]}" --with-libsodium=yes; make -j${CPUS} install)

# dep: libvigor
curl -Ls https://github.com/jhunt/libvigor/releases/download/v${WANT_LIBVIGOR}/libvigor-${WANT_LIBVIGOR}.tar.gz | tar -xz
(cd libvigor-${WANT_LIBVIGOR}; ./configure "${CONFIG_OPTS[@]}"; make -j${CPUS} install)

# dep: ztk
curl -Ls https://github.com/jhunt/ztk/releases/download/v${WANT_ZTK}/ztk-${WANT_ZTK}.tar.gz | tar -xz
(cd ztk-${WANT_ZTK}; ./configure "${CONFIG_OPTS[@]}"; make -j${CPUS} install)

export PATH="$PATH:${BUILD_PREFIX}/bin"
./bootstrap
./configure "${CONFIG_OPTS[@]}"

make -j${CPUS}
make -j${CPUS} check
make           install

set +x
echo ; echo "##########################################################"
check_cla
