#include "test.h"
#include <sys/mman.h>
#include <zmq.h>
#include <pthread.h>

/* FIXME: move this into ctap proper */
#define CHECK(x,msg) if (!(x)) BAIL_OUT(msg)

static int file_is(const char *path, const char *expect, const char *msg)
{
	FILE *io = fopen(path, "r");
	CHECK(io, "failed to open file for file_is() check");

	fseek(io, 0, SEEK_END);
	size_t len = ftell(io);
	rewind(io);

	char *actual = mmap(NULL, len, PROT_READ, MAP_PRIVATE, fileno(io), 0);
	CHECK(actual, "failed to mmap target file for file_is() check");

	is_int(len, strlen(expect), "%s (file length)", msg);
	is_string(actual, expect, "%s", msg);

	return 0;
}

TESTS {
	server_t svr;
	int rc;
	void *z;
	pthread_t tid;

	mkdir("t/tmp", 0755);
	svr.dumpfile_fmt = "t/tmp/dump.%s";

	CHECK(svr.zmq = zmq_ctx_new(),
		"failed to create a new 0MQ context");

	CHECK(pthread_create(&tid, NULL, db_manager, &svr) == 0,
		"failed to spin up db manager thread");

	CHECK(z = zmq_socket(svr.zmq, ZMQ_DEALER),
		"failed to create mock db manager test socket");
	CHECK(zmq_connect(z, DB_MANAGER_ENDPOINT) == 0,
		"failed to connect to db manager socket");

	/* ----------------------------- */

	pdu_t *p;
	char *ts = string("%i", time_s());
	char *s;

	/* send an invalid PDU */
	p = pdu_make("@INVALID!", 2, "foo", "bar");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent [@INVALID!] PDU to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "ERROR", "db manager replied with an [ERROR]");
	is_string(s = pdu_string(p, 1), "Invalid PDU", "Error message returned"); free(s);
	pdu_free(p);

	/* send test.state.0 initial ok */
	p = pdu_make("UPDATE", 4, ts, "test.state.0", "0", "all good");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent [UPDATE] PDU to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "OK", "db manager replied with an [OK]");
	pdu_free(p);

	/* send test.state.1 initial crit */
	p = pdu_make("UPDATE", 4, ts, "test.state.1", "2", "critically-ness");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent 2nd [UPDATE] PDU to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "OK", "db manager replied with an [OK]");
	pdu_free(p);

	/* dump the state file (to /t/tmp/dump.test) */
	unlink("t/tmp/dump.test");
	p = pdu_make("DUMP", 1, "test");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent [DUMP] PDU to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "DUMP", "db manager replied with a [DUMP]");
	is_string(s = pdu_string(p, 1), "t/tmp/dump.test", "[DUMP] reply returned file path"); free(s);
	pdu_free(p);

	file_is("t/tmp/dump.test",
		s = string("---\n"
		           "# generated by bolo\n"
		           "test.state.0:\n"
		           "  status:    OK\n"
		           "  message:   all good\n"
		           "  last_seen: %s\n"
		           "  fresh:     yes\n"
		           "test.state.1:\n"
		           "  status:    CRITICAL\n"
		           "  message:   critically-ness\n"
		           "  last_seen: %s\n"
		           "  fresh:     yes\n", ts, ts),
		"dumped YAML file"); free(s);

	/* get state of test.state.1 via [STATE] */
	p = pdu_make("STATE", 1, "test.state.1");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent [STATE] query to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "STATE", "db manager replied with a [STATE]");
	is_string(s = pdu_string(p, 1), "test.state.1",    "STATE[0] is state name"); free(s);
	is_string(s = pdu_string(p, 2), ts,                "STATE[1] is last seen ts"); free(s);
	is_string(s = pdu_string(p, 3), "yes",             "STATE[2] is freshness boolean"); free(s);
	is_string(s = pdu_string(p, 4), "CRITICAL",        "STATE[3] is status"); free(s);
	is_string(s = pdu_string(p, 5), "critically-ness", "STATE[4] is summary"); free(s);
	pdu_free(p);

	/* get non-existent state via [STATE] */
	p = pdu_make("STATE", 1, "fail.enoent//0");
	rc = pdu_send_and_free(p, z);
	is_int(rc, 0, "sent [STATE] query to db manager");

	p = pdu_recv(z);
	isnt_null(p, "received reply PDU from db manager");
	is_string(pdu_type(p), "ERROR", "db manager replied with an [ERROR]");
	is_string(s = pdu_string(p, 1), "State Not Found", "Error message returned"); free(s);
	pdu_free(p);

	/* ----------------------------- */
	pthread_cancel(tid);
	zmq_close(z);
}
