#!/bin/bash
source ${srcdir:-.}/t/lib
need_command z{sub,pub,push}
tmpfs

BCACHE_BROADCAST="ipc://${ROOT}/bolo-cache.relay.sock"
BCACHE_CONTROLLER="ipc://${ROOT}/bolo-cache.control.sock"
BROADCAST="ipc://${ROOT}/bolo.broadcast.sock"

./bolo cache -Fvvvvvv -e ${BROADCAST} -B ${BCACHE_BROADCAST} -l ${BCACHE_CONTROLLER} > ${ROOT}/bolo-cache.out 2>&1 &
BCACHE_PID=$!
clean_pid ${BCACHE_PID}
diag_file ${ROOT}/bolo-cache.out

zsub --connect ${BCACHE_BROADCAST} >${ROOT}/early.out 2>&1 &
EARLY_SUB_PID=$!
clean_pid ${EARLY_SUB_PID}
diag_file ${ROOT}/early.out

(
	sleep 1; # allow cache subscriber to SUBSCRIBE
	ts=$(date +%s)
	echo "STATE|sys.cpu|${ts}|fresh|0|all good"
	echo "TRANSITION|sys.cpu|${ts}|fresh|0|all good"
	echo "COUNTER|${ts}|a.random.counter|42"
	echo "SAMPLE|${ts}|a.random.sample|4|10|200|900|100|20"
	echo "RATE|${ts}|a.random.rate|1|67"
	echo "EVENT|${ts}|reboot|server rebooted"
	exit
) | zpub --bind ${BROADCAST} --timeout 200 >${ROOT}/broadcast.out 2>&1 &
BROADCAST_PID=$!
clean_pid ${BROADCAST_PID}
diag_file ${ROOT}/broadcast.out
sleep 2

kill -TERM ${EARLY_SUB_PID}

zsub --connect ${BCACHE_BROADCAST} > ${ROOT}/late.out 2>&1 &
LATE_SUB_PID=$!
clean_pid ${LATE_SUB_PID}
diag_file ${ROOT}/late.out
sleep 1

echo "REPEAT" | zpush --timeout 100 --connect ${BCACHE_CONTROLLER}
sleep 1
kill -TERM ${LATE_SUB_PID}

########################################################################

grep -q "STATE|sys.cpu|.*|fresh|0|all good" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the sys.cpu STATE"
grep -q "$(grep "STATE|sys.cpu" ${ROOT}/early.out)" ${ROOT}/late.out \
	|| bail "late subscriber did not get rebroadcast of sys.cpu STATE"

grep -q "COUNTER|.*|a.random.counter|42" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the a.random.counter COUNTER"
grep -q "$(grep "a.random.counter" ${ROOT}/early.out)" ${ROOT}/late.out \
	|| bail "late subscribe did not get rebroadcast of a.random.counter COUNTER"

grep -q "SAMPLE|.*|a.random.sample|4|10|200|900|100|20" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the a.random.sample SAMPLE"
grep -q "$(grep "a.random.sample" ${ROOT}/early.out)" ${ROOT}/late.out \
	|| bail "late subscribe did not get rebroadcast of a.random.sample SAMPLE"

grep -q "RATE|.*|a.random.rate|1|67" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the a.random.rate RATE"
grep -q "$(grep "a.random.rate" ${ROOT}/early.out)" ${ROOT}/late.out \
	|| bail "late subscribe did not get rebroadcast of a.random.rate RATE"

grep -q "TRANSITION|sys.cpu" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the sys.cpu STATE TRANSITION"
grep -q "TRANSITION" ${ROOT}/late.out \
	&& bail "\`bolo cache' should NOT rebroadcast ephemeral TRANSITION PDUs"

grep -q "EVENT|.*|reboot" ${ROOT}/early.out \
	|| bail "early subscriber did not receive the reboot EVENT"
grep -q "EVENT" ${ROOT}/late.out \
	&& bail "\`bolo cache' should NOT rebroadcast ephemeral EVENT PDUs"

exit 0
