/*
  Copyright 2015 James Hunt <james@jameshunt.us>

  This file is part of Bolo.

  Bolo is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.

  Bolo is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
  details.

  You should have received a copy of the GNU General Public License along
  with Bolo.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "test.h"

TESTS {
	DEBUGGING("t/events");
	NEED_FS();
	TIMEOUT(5);

	server_t *svr = CONFIGURE("max.events 3\n");

	void *zmq;
	CHECK(zmq = zmq_ctx_new(),
		"failed to create a new 0MQ context");

	KERNEL(zmq, svr);
	void *super  = SUPERVISOR(zmq);
	void *client = CLIENT(zmq);
	void *mgr    = MANAGER(zmq);

	/* ----------------------------- */

	send_ok(pdu_make("EVENT", 3, "10001", "event.1", "the first event"), client);
	send_ok(pdu_make("EVENT", 3, "10002", "event.2", "the second event"), client);
	send_ok(pdu_make("EVENT", 3, "10003", "event.3", "the third event"), client);

	/* wait for PULL socket */
	sleep_ms(50);

	send_ok(pdu_make("GET.EVENTS", 1, "0"), mgr);
	recv_ok(mgr, "EVENTS", 1,
		"---\n"
		"# generated by bolo\n"
		"- name:  event.1\n"
		"  when:  10001\n"
		"  extra: the first event\n"
		"- name:  event.2\n"
		"  when:  10002\n"
		"  extra: the second event\n"
		"- name:  event.3\n"
		"  when:  10003\n"
		"  extra: the third event\n");

	send_ok(pdu_make("GET.EVENTS", 1, "10003"), mgr);
	recv_ok(mgr, "EVENTS", 1,
		"---\n"
		"# generated by bolo\n"
		"- name:  event.3\n"
		"  when:  10003\n"
		"  extra: the third event\n");

	/* send a fourth event */
	send_ok(pdu_make("EVENT", 3, "10004", "event.4", "the fourth event"), client);

	send_ok(pdu_make("GET.EVENTS", 1, "0"), mgr);
	recv_ok(mgr, "EVENTS", 1,
		"---\n"
		"# generated by bolo\n"
		"- name:  event.2\n"
		"  when:  10002\n"
		"  extra: the second event\n"
		"- name:  event.3\n"
		"  when:  10003\n"
		"  extra: the third event\n"
		"- name:  event.4\n"
		"  when:  10004\n"
		"  extra: the fourth event\n");

	/* ----------------------------- */

	pdu_send_and_free(pdu_make("TERMINATE", 0), super);
	zmq_close(super);
	zmq_close(client);
	zmq_close(mgr);
	zmq_ctx_destroy(zmq);
}
