#!/usr/bin/env bash
source t/lib ; trap "cleanup" EXIT TERM INT
tmpfs

LISTENER="ipc://${ROOT}/bolo.listener.sock"
BROADCAST="ipc://${ROOT}/bolo.broadcast.sock"

while true; do
	ts=$(date +%s)
	echo "COUNTER|${ts}|a.random.counter|42"
	echo "SAMPLE|${ts}|a.random.sample|4|10|200|900|100|20"
	echo "RATE|${ts}|a.random.rate|1|67"
	echo "STATE|${ts}|a.random.state|fresh|0|all good"
	echo "TRANSITION|${ts}|a.random.state|fresh|0|all good"
	echo "EVENT|${ts}|a.random.event|extra data"

	echo "COUNTER|${ts}|bogon"
	echo "SAMPLE|${ts}|bogon"
	echo "RATE|${ts}|bogon"
	echo "STATE|${ts}|bogon"
	echo "TRANSITION|${ts}|bogon"
	echo "EVENT|${ts}|bogon"

	echo "BOGON|${ts}|bogon"

	sleep 1
done | zpub --bind ${BROADCAST} --timeout 200 >${ROOT}/broadcast.out 2>&1 &
BROADCAST_PID=$!
clean_pid ${BROADCAST_PID}
diag_file ${ROOT}/broadcast.out

zpull --bind ${LISTENER} >${ROOT}/submitted.out 2>&1 &
PULL_PID=$!
clean_pid ${PULL_PID}
diag_file ${ROOT}/submitted.out

./bolo2meta -Fvvvvvvvvvvv -P x -e ${BROADCAST} -S ${LISTENER} >${ROOT}/bolo2meta.out 2>&1 &
BOLO2META_PID=$!
clean_pid ${BOLO2META_PID}
diag_file ${ROOT}/bolo2meta.out

sleep 6
kill -TERM ${BROADCAST_PID} ${PULL_PID} ${BOLO2META_PID}

for metric in state sample event counter transition rate; do
	grep -q "^COUNTER|.*|x:${metric}|" ${ROOT}/submitted.out \
		|| bail "bolo2rrd didn't submit the '${metric}' COUNTER metric"
	grep -q "^COUNTER|.*|x:bogon.${metric}|" ${ROOT}/submitted.out \
		|| bail "bolo2rrd didn't submit the 'bogon.${metric}' COUNTER metric"
done
grep -q "^COUNTER|.*|x:bogon.unknown|" ${ROOT}/submitted.out \
	|| bail "bolo2rrd didn't submit the 'bogon.unknown' COUNTER metric"

exit 0
